---
- name: Prepare
  hosts: all
  tags:
    - gsi_ca
  gather_facts: false
  become: yes
  become_user: root
  vars: &common_variables
    SHARED_KEY: .gfarm_shared_key
    SYS_USER: "{{ ansible_user }}"
    SYS_HOME: "/home/{{ SYS_USER }}"
    USERS:
      - "{{ SYS_USER }}"
      - user1
      - user2
    ALL_USERS: "{{ USERS + ['_gfarmmd', '_gfarmfs'] }}"
    SETUP_TMP: "{{ SYS_HOME }}/gfarm-setup-tmp"
    GSDIR: /etc/grid-security
    TLSDIR: /etc/pki/tls
    CERTDIR: "{{ GSDIR }}/certificates"
    HOSTCERT: "{{ GSDIR }}/hostcert.pem"
    SERVICE: gfsd
    GFSD_CERT: "{{ GSDIR }}/{{ SERVICE }}/{{ SERVICE }}cert.pem"
    DIGEST: sha256
    SIGN_WORKDIR: "{{ SETUP_TMP }}/ca_sign"
    CA_DIR: /var/lib/globus/simple_ca
  tasks:
    - name: Install rsync
      package:
        name: rsync
        state: present

######################################################################
- name: Install gfarm
  hosts: gfarm
  tags:
    - gfarm
  gather_facts: false
  vars:
    <<: [*common_variables]
  # TODO rsync and distclean?
  serial: 1  # to build on same /SRC directory ...
  tasks:
    - name: install gfarm
      command: bash /SCRIPT/install-gfarm.sh --no-distclean
      #command: date  #TODO
    - name: Create local users
      become: yes
      become_user: root
      user:
        name: "{{ item }}"
        state: present
      loop: "{{ USERS }}"

######################################################################
- name: Setup SASL for servers
  hosts: group_gfmd, group_gfsd
  gather_facts: no
  #vars: *common_variables
  tasks:
    - name: Run pkg-config
      shell: pkg-config --variable=libdir libsasl2
      register: pkgconfig_out
    - name: Display pkgconfig_out
      debug:
        var: pkgconfig_out
    - name: Create sasl2/gfarm.conf for server
      become: yes
      become_user: root
      copy:
        content: |
          log_level: 7
          mech_list: XOAUTH2 ANONYMOUS
          xoauth2_scope: hpci
          xoauth2_aud: hpci
          xoauth2_user_claim: hpci.id
        dest: "{{ pkgconfig_out.stdout_lines[0] }}/sasl2/gfarm.conf"
    #- name: cat
    #  shell: cat "{{ pkgconfig_out.stdout_lines[0] }}/sasl2/gfarm.conf"

- name: Setup SASL for all hosts
  hosts: gfarm
  gather_facts: no
  tasks:
    - name: Run pkg-config
      shell: pkg-config --variable=libdir libsasl2
      register: pkgconfig_out
    - name: Display pkgconfig_out
      debug:
        var: pkgconfig_out
    - name: Create sasl2/gfarm.conf for client
      become: yes
      become_user: root
      copy:
        content: |
          xoauth2_user_claim: hpci.id
        dest: "{{ pkgconfig_out.stdout_lines[0] }}/sasl2/gfarm-client.conf"
    - name: create empty sasldb2 database
      # because the gdbm backend of Cyrus SAL (e.g. on RHEL9) needs this
      # although the berkeley DB backend does NOT
      become: yes
      become_user: root
      shell: saslpasswd2 -d -u NOT-EXIST NOT-EXIST
    - name: sasldb2
      # XXX - SASL XOAUTH2 fails in gfsd on ubuntu due to the error
      # "unable to open Berkeley db /etc/sasldb2: Permission denied"
      become: yes
      become_user: root
      shell: |
        set -e
        if [ -e /etc/sasldb2 ]; then
          chown _gfarmfs /etc/sasldb2
          exit 0
        elif [ -e /etc/sasl2/sasldb2 ]; then
          chown _gfarmfs /etc/sasl2/sasldb2
          exit 0
        fi
        exit 1

######################################################################
- name: Create .gfarm_shared_key
  hosts: gfmd1
  gather_facts: no
  vars: *common_variables
  tasks:
    - name: Create keys for users
      become: yes
      become_user: root
      shell: sudo -u {{ item }} gfkey -f -p 31536000
      loop: "{{ ALL_USERS }}"
    - name: Copy key to local
      become: yes
      become_user: root
      fetch:
        src: "/home/{{ item }}/{{ SHARED_KEY }}"
        dest: "{{ SETUP_TMP }}/{{ SHARED_KEY }}-{{ item }}"
        flat: yes
      loop: "{{ ALL_USERS }}"

- name: Copy .gfarm_shared_key to servers
  hosts: group_gfmd:group_gfsd:!gfmd1
  gather_facts: no
  vars: *common_variables
  tasks:
    - name: Copy keys
      become: yes
      become_user: root
      copy:
        src: "{{ SETUP_TMP }}/{{ SHARED_KEY }}-{{ item }}"
        dest: "/home/{{ item }}/{{ SHARED_KEY }}"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: "0600"
      loop: "{{ ALL_USERS }}"

- name: Copy .gfarm_shared_key to clients
  hosts: group_gfclient
  gather_facts: no
  vars: *common_variables
  tasks:
    - name: Copy keys
      become: yes
      become_user: root
      copy:
        src: "{{ SETUP_TMP }}/{{ SHARED_KEY }}-{{ item }}"
        dest: "/home/{{ item }}/{{ SHARED_KEY }}"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: "0600"
      loop: "{{ USERS }}"

######################################################################
- name: Build CA environment for GSI
  hosts: manage
  gather_facts: no
  vars: *common_variables
  tags: gsi_ca
  tasks:
    - name: Install globus-simple-ca
      become: yes
      become_user: root
      package:
        name: globus-simple-ca
        state: present
    - name: Initialize CA
      shell: bash -x /SCRIPT/setup-globus-simple-ca.sh
      register: ca_result
    - name: set fact
      set_fact:
        gsi_ca_hash: "{{ ca_result.stdout }}"
    - name: id
      become: yes
      become_user: root
      command: id

    - name: Copy cacert.pem
      become: yes
      become_user: root
      shell: |
        set -e
        DEST="{{ SYS_HOME }}/cacert.pem"
        cp -f "{{ CA_DIR }}/cacert.pem" "$DEST"
        chown "{{ SYS_USER }}:{{ SYS_USER }}" "$DEST"

- name: Request GSI server certificates
  #hosts: group_gfmd group_gfsd  #TODO jwtserver keycloak
  hosts: gfarm
  gather_facts: no
  vars:
    <<: [*common_variables]
    CA_HASH: "{{ hostvars['manage']['gsi_ca_hash'] }}"
  tags: gsi_ca
  tasks:
    - name: debug
      debug:
        var: gsi_ca_hash
    - name: mkdir
      become: yes
      become_user: root
      file:
        path: "{{ CERTDIR }}"
        state: directory
    - name: sync
      become: yes
      become_user: root
      synchronize:
        src: "{{ CERTDIR }}"
        dest: "{{ CERTDIR }}"
    - name: grid-default-ca
      become: yes
      become_user: root
      shell: grid-default-ca -ca {{ CA_HASH }}

    - name: patch for grid-cert-requiest
      become: yes
      become_user: root
      command: sed -i 's/:\/var\/adm\/wtmp:\/var\/log\/messages//' /usr/bin/grid-cert-request

    - name: Check the existence of hostcert
      become: yes
      become_user: root
      stat:
        path: "{{ HOSTCERT }}"
      register: hostcert_stat

    - name: hostcert request
      become: yes
      become_user: root
      shell: yes | grid-cert-request -host {{ inventory_hostname }}
      when: not hostcert_stat.stat.exists

    - name: Check the existence of gfsdcert
      become: yes
      become_user: root
      stat:
        path: "{{ GFSD_CERT }}"
      register: gfsdcert_stat

    - name: gfsdcert request
      become: yes
      become_user: root
      shell: yes | grid-cert-request -service {{ SERVICE }} -host {{ inventory_hostname }}
      when: not gfsdcert_stat.stat.exists

    - name: Create local SIGN_WORKDIR
      file:
        path: "{{ SIGN_WORKDIR }}/{{ inventory_hostname }}"
        state: directory
      delegate_to: localhost

    - name: fetch hostcert request
      become: yes
      become_user: root
      fetch:
        src: "{{ GSDIR }}/hostcert_request.pem"
        dest: "{{ SIGN_WORKDIR }}/{{ inventory_hostname }}/"
        flat: yes

    - name: fetch gfsdcert request
      become: yes
      become_user: root
      fetch:
        src: "{{ GSDIR }}/{{ SERVICE }}/{{ SERVICE }}cert_request.pem"
        dest: "{{ SIGN_WORKDIR }}/{{ inventory_hostname }}/"
        flat: yes

- name: Sign and copy certificates for servers
  hosts: gfarm
  gather_facts: no
  vars:
    <<: [*common_variables]
  tags: gsi_ca
  serial: 1  # batch size 1 to sign for X.509 serial number
  tasks:
    - name: Sign requests for servers
      become: yes
      become_user: root
      shell: |
        OUT="{{ SIGN_WORKDIR }}/{{ inventory_hostname }}/{{ item }}.pem"
        [ -f $OUT ] || cat /CONF/ca-password.txt | grid-ca-sign -in {{ SIGN_WORKDIR }}/{{ inventory_hostname }}/{{ item }}_request.pem -out $OUT -passin stdin -md {{ DIGEST }}
      loop:
        - hostcert
        - "{{ SERVICE }}cert"
      delegate_to: localhost

    - name: Copy host certificate
      become: yes
      become_user: root
      copy:
        src: "{{ SIGN_WORKDIR }}/{{ inventory_hostname }}/hostcert.pem"
        dest: "{{ GSDIR }}/"

    - name: Copy gfsd certificate
      become: yes
      become_user: root
      copy:
        src: "{{ SIGN_WORKDIR }}/{{ inventory_hostname }}/{{ SERVICE }}cert.pem"
        dest: "{{ GSDIR }}/{{ SERVICE }}/"

    - name: chown gfsd key for _gfarmfs
      become: yes
      become_user: root
      file:
        path: "{{ GSDIR }}/{{ SERVICE }}/"
        recurse: true
        owner: _gfarmfs
        group: _gfarmfs

- name: Create GSI clinet certificates
  hosts: gfclient1
  tags: gsi_ca
  gather_facts: no
  vars:
    <<: [*common_variables]
    CA_HASH: "{{ hostvars['manage']['gsi_ca_hash'] }}"
  tasks:
    - name: Request usercert
      become: yes
      become_user: root
      shell: |
        set -e
        u={{ item }}
        CERT=/home/$u/.globus/usercert.pem
        [ -f $CERT ] && exit 0
        REQ=/home/$u/.globus/usercert_request.pem
        rm -f $REQ
        sudo -u {{ item }} grid-cert-request -cn $u -nopw
      loop: "{{ USERS }}"

    - name: fetch usercert requests
      become: yes
      become_user: root
      fetch:
        src: "/home/{{ item }}/.globus/usercert_request.pem"
        dest: "{{ SIGN_WORKDIR }}/usercert_request-{{ item }}.pem"
        flat: yes
      loop: "{{ USERS }}"

    - name: Sign for users
      become: yes
      become_user: root
      shell: |
        IN="{{ SIGN_WORKDIR }}/usercert_request-{{ item }}.pem"
        OUT="{{ SIGN_WORKDIR }}/usercert-{{ item }}.pem"
        [ -f $OUT ] || cat /CONF/ca-password.txt | grid-ca-sign -in $IN -out $OUT -passin stdin -md {{ DIGEST }}
      loop: "{{ USERS }}"
      delegate_to: localhost

    - name: Send certificate for users
      become: yes
      become_user: root
      copy:
        src: "{{ SIGN_WORKDIR }}/usercert-{{ item }}.pem"
        dest: "/home/{{ item }}/.globus/usercert.pem"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: "0600"
      loop: "{{ USERS }}"

    - name: Fetch .globus
      become: yes
      become_user: root
      fetch:
        src: "/home/{{ item.0 }}/.globus/{{ item.1 }}"
        dest: "{{ SETUP_TMP }}/dot_globus/{{ item.0 }}/{{ item.1 }}"
        flat: yes
        mode: "0600"
      with_nested:
        - "{{ USERS }}"
        - [ "usercert.pem", "usercert_request.pem", "userkey.pem"]
    - name: chmod -R go-rwx .globus
      become: yes
      become_user: root
      command: chmod -R go-rwx "{{ SETUP_TMP }}/dot_globus/"
      delegate_to: localhost
      run_once: true

- name: Synchronize .globus
  hosts: gfarm
  tags: gsi_ca
  gather_facts: no
  vars:
    <<: [*common_variables]
  tasks:
    - name: synchronize .globus
      become: yes
      become_user: root
      synchronize:
        src: "{{ SETUP_TMP }}/dot_globus/{{ item }}/"
        dest: "/home/{{ item }}/.globus/"
      loop: "{{ USERS }}"

######################################################################
- name: Setup TLS environment
  hosts: gfarm
  gather_facts: yes  # for ansible_os_family
  vars:
    <<: [*common_variables]
  tags: tls
  tasks:
    - name: Create TLS directories
      become: yes
      become_user: root
      file:
        path: "{{ TLSDIR }}/{{ item }}"
        state: directory
      loop:
        - certs
        - private

    - name: Symlink for certificates and keys
      become: yes
      become_user: root
      file:
        src: "{{ GSDIR }}/{{ item.0 }}"
        dest: "{{ TLSDIR }}/{{ item.1 }}"
        state: link
      loop:  # [src, dest]
        - ["certificates", "certs/gfarm"]
        - ["hostcert.pem", "private/gfmd.key"]
        - ["gfsd/gfsdcert.pem", "certs/gfsd.crt"]
        - ["gfsd/gfsdkey.pem", "certs/gfsd.key"]

    - name: Copy cacert.pem to hosts
      copy:
        src: "{{ SYS_HOME }}/cacert.pem"
        dest: "{{ SYS_HOME }}/cacert.pem"

    - name: GSI CA to TLS
      become: yes
      become_user: root
      block:
        - name: update-ca-certificates for Debian family
          shell: |
            set -e
            mkdir -p /usr/share/ca-certificates/gfarm
            cp {{ SYS_HOME }}/cacert.pem /usr/share/ca-certificates/gfarm/
            update-ca-certificates
          # args:
          #   executable: /bin/bash
          when: ansible_os_family == "Debian"
        - name: update-ca-trust for RHEL family
          shell:
            set -e
            cp {{ SYS_HOME }}/cacert.pem /usr/share/pki/ca-trust-source/anchors/
            update-ca-trust
          when: ansible_os_family == "RHEL"
          # args:
          #   executable: /bin/bash

######################################################################
# - name: Configure gfarm
#   hosts: gfarm
#   gather_facts: yes  # for ansible_os_family
#   vars:
#     <<: [*common_variables]
#   tags: gfarm
#   tasks:
#     - name:
