---
- name: Run ssh-keyscan on inventory hosts
  hosts: gfarm
  gather_facts: false

  tasks:
    - name: Run ssh-keyscan
      raw: bash /SCRIPT/ssh-keyscan-update.sh ~/.ssh/known_hosts {{ hostvars[inventory_hostname]['ansible_host'] | default(inventory_hostname) }}
      delegate_to: localhost
