INV = tmp-ansible-inventory.yaml

ansible-init:
	bash ./setup-ansible.sh
ansible-ping:
	bash ./ansible-ping.sh
ansible-gfarm-install:
	bash ./ansible-gfarm-install.sh
ansible-gfarm-setup:
	bash ./ansible-gfarm-setup.sh
