---
- name: Distribute SSH Private Key and known_hosts
  hosts: all
  gather_facts: false
  tasks:
    - name: Send SSH private key
      copy:
        src: ../id_ecdsa
        dest: /home/{{ ansible_user }}/.ssh/id_ecdsa
        mode: 0600
    - name: Send SSH known_hosts
      copy:
        src: ./tmp-known_hosts
        dest: /home/{{ ansible_user }}/.ssh/known_hosts
        mode: 0600
